---
title: "Assigment1_Part3"
author: "AI Casas"
date: "4/20/2020"
output: pdf_document
---

```{r}
getwd()
setwd("/Users/ppm/Desktop/R Course/First/specdata")
getwd()

```

```{r}
p1 <- read.csv("001.csv")

sn1 <- p1[, "sulfate"]
sn2 <- p1[, "nitrate"]
cor(sn1, sn2, use = "complete.obs")


```

```{r}
sn1 <- p1[complete.cases(p1), c("sulfate", "nitrate")]
cor(sn1$sulfate, sn1$nitrate)


```

FUNCION Assigment 1_Part3
```{r}
corr <- function(directory, threshold, id = 1:332){
  docs <- dir(directory)
  docs <- docs[id] 
  allnobs <- c()

  
  for (doc in docs) {
    df <- read.csv(file.path(directory, doc))
    p2 <- complete.cases(df)
    p3 <- p2[p2]
    ln <- length(p3)
    allnobs <- c(allnobs, ln)
    
  }

df_com1 <- data.frame(id, allnobs)
df_com2 <- df_com1[allnobs > threshold, ]
ids <- df_com2[, "id"]
print(ids)

docs2 <- dir(directory)
new_docs <- docs2[ids]
cor_f <- c()
  
  for(doc in new_docs){
    new_df <- read.csv(file.path(directory, doc))
    sn1 <- new_df[complete.cases(new_df), c("sulfate", "nitrate")]
    cor_acc <- cor(sn1$sulfate, sn1$nitrate)
    cor_f <- c(cor_f, cor_acc)
  
  }
return(cor_f)
}
cr <- corr("specdata", 150)
head(cr)

```
Week2_Quiz
```{r}
cr <- corr("specdata", 0)                
cr <- sort(cr)   
RNGversion("3.5.1")
set.seed(868)                
out <- round(cr[sample(length(cr), 5)], 4)
print(out)
```

Week2_Quiz
```{r}
cr <- corr("specdata", 129)                
cr <- sort(cr)                
n <- length(cr)    
RNGversion("3.5.1")
set.seed(197)                
out <- c(n, round(cr[sample(n, 5)], 4))
print(out)
```

Week2_Quiz
```{r}
cr <- corr("specdata", 129)                
cr <- sort(cr)                
n <- length(cr)    
RNGversion("3.5.1")
set.seed(197)                
out <- c(n, round(cr[sample(n, 5)], 4))
print(out)
```

Week2_Quiz
```{r}
cr <- corr("specdata", 2000)                
n <- length(cr)                
cr <- corr("specdata", 1000)                
cr <- sort(cr)
print(c(n, round(cr, 4)))
```

Pruebas de ciertas partes de la funcion
```{r}
  for(doc in new_docs){
  new_df <- read.csv(file.path(directory, doc))
  sn1 <- new_df[complete.cases(p1), c("sulfate", "nitrate")]
  cor_acc <- cor(sn1$sulfate, sn1$nitrate)
  cor_f <- c(cor_f, cor_acc)
```


```{r}
    sn <- read.csv("001.csv")
    sn1 <- sn[complete.cases(sn), c("sulfate", "nitrate")]
    cor_acc <- cor(sn1$sulfate, sn1$nitrate)
    cor_acc
   
```

```{r}
setwd("/Users/ppm/Desktop/R Course/First")
```

```{r}
?head
```

