---
title: "Untitled"
author: "AI Casas"
date: "4/27/2020"
output: pdf_document
---

Part 1: Plot the 30-day mortality rates for heart attack

```{r}
outcome <- read.csv("outcome-of-care-measures.csv")
summary(outcome)
head(outcome)
```

```{r}
ncol(outcome)
```

```{r}
outcome <- read.csv("outcome-of-care-measures.csv")
outcome[, 11] 
prr <- as.numeric(outcome[, 11])
class(prr)


```

```{r}
hist(outcome[, 11])
```

```{r}
outcome <- read.csv("outcome-of-care-measures.csv")
outcome
outcome[, c("State", "Hospital.Name", "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack")]
outcome [, "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack"] <- as.numeric(outcome[, "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack"])
outcome [, 11]

```

```{r}
outcome [, 11] <- as.numeric(outcome[, 11])
outcome [, 11]

outcome$State
```
```{r}
min(outcome[, 11])
```

```{r}
best <- function(state){
  out <- read.csv("outcome-of-care-measures.csv")
  pr1 <- out[out$State==state, "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack"]
  pr2 <- as.numeric(pr1)
  min(pr2)
}

best("AL")

```



```{r}

```

```{r}

  
```

```{r}
best <- function(state, outcome){
df <- read.csv("outcome-of-care-measures.csv")
out_emp <- c("heart attack", "heart failure", "pneumonia")


  if (state %in% df$State){
    
  } else {
    print("invalid State")
  }
  
  if(outcome %in% out_emp){
    
  }else {
    print("invalid Outcome")
  }
  
  print("OK")
  
  if (outcome == "heart attack"){
  df[, 11] <- as.numeric(df[, 11])
  df_sub <- df[df$State==state, c("Hospital.Name", "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack")]

  df_HA1 <- df_sub[min(df_sub["Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack"]), "Hospital.Name"]
  df_HA1
  } else{
    print ("no option")
  }
  
  
  
  if (outcome == "heart failure"){
  df[, 11] <- as.numeric(df[, 11])
  df_sub <- df[df$State==state, c("Hospital.Name", "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure")]

  df_HA2 <- df_sub[min(df_sub["Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure"]), "Hospital.Name"]
  df_HA2
  } else {
    print ("no option")
  }
  
  if (outcome == "pneumonia"){
  df[, 11] <- as.numeric(df[, 11])
  df_sub <- df[df$State==state, c("Hospital.Name", "Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia")]

  df_HA3 <- df_sub[min(df_sub["Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia"]), "Hospital.Name"]
  df_HA3
  } else {
    print ("no option")
  }
  
}

best("AR", "heart attack")

    
```

OPTION 1

```{r}
best <- function(state, outcome){
df <- read.csv("outcome-of-care-measures.csv")
out_emp <- c("heart attack", "heart failure", "pneumonia")


  if (state %in% df$State){
    
  } else {
    print("invalid State")
    stop()
  }
  
  if(outcome %in% out_emp){
    
  }else {
    print("invalid Outcome")
    stop()
  }
  
  print("OK")

  
  if (outcome == "heart attack"){
  df2 <- data.frame(df[df$State == state,])
  min_row <- which(as.numeric(df2[, 11]) == min(as.numeric(df2[,11]), na.rm = TRUE)) 
  df2[min_row,2]
 
 } else if (outcome == "heart failure"){
    df3 <- data.frame(df[df$State == state,])
    min_row <- which(as.numeric(df3[, 17]) == min(as.numeric(df3[,17]), na.rm = TRUE)) 
    df3[min_row,2]
    
  } else (outcome == "pneumonia"){
    df4 <- data.frame(df[df$State == state,])
    min_row <- which(as.numeric(df4[, 23]) == min(as.numeric(df4[,23]), na.rm = TRUE)) 
    df4[min_row,2]
   } 

}
best("MD", "pneumonia")

```



```{r}
df <- read.csv("outcome-of-care-measures.csv")
df[, 11] <- as.numeric(df[, 11])
df_sub <- df[df$State=="MD", c("Hospital.Name", "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack")]
df_sub
df_HA <- df_sub[which.min(df_sub[,"Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack"]), "Hospital.Name"]
df_HA

```

```{r}


```

```{r}

```

```{r}

  
```

GOOD external
```{r}
best<- function(state, outcome)
{
  outcome1 <- read.csv("outcome-of-care-measures.csv",
                       colClasses = "character")
  if(!any(state == outcome1$State)){
    stop("invalid state")}
  else if((outcome %in% c("heart attack", "heart failure",
                          "pneumonia")) == FALSE) {
    stop(print("invalid outcome"))
  }
  outcome2 <- subset(outcome1, State == state)
  if (outcome == "heart attack") {
    colnum <- 11
  }
  else if (outcome == "heart failure") {
    colnum <- 17
  }
  else {
    colnum <- 23
  }
  min_row <- which(as.numeric(outcome2[ ,colnum]) == 
                     min(as.numeric(outcome2[ ,colnum]), na.rm = TRUE))

  hospitals <- outcome2[min_row,2]
  hospitals <- sort(hospitals)
  return(hospitals[1])
}
best("MD", "heart attack")
```


```{r}
best <- function(state, outcome){
df <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
out_emp <- c("heart attack", "heart failure", "pneumonia")


  if (state %in% df$State){
    
  } else {
    print("invalid State")
    stop()
  }
  
  if(outcome %in% out_emp){
    
  }else {
    print("invalid Outcome")
    stop()
  }
  
  
  if (outcome == "heart attack"){
    df2 <- data.frame(df[df$State == state, c("Hospital.Name", "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack")])
    df2$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack <-      as.numeric(df2$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack)
    df3 <- order(df2$Hospital.Name)
    df4 <- df2[df3,]
    df5 <- order(df4$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack)
    df6 <- df4[df5,]
    
    return(df6[1,1])

    } else if (outcome == "heart failure"){
    df2 <- data.frame(df[df$State == state, c("Hospital.Name", "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure")])
    df2$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure <-      as.numeric(df2$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure)
    df3 <- order(df2$Hospital.Name)
    df4 <- df2[df3,]
    df5 <- order(df4$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure)
    df6 <- df4[df5,]
    
    return(df6[1,1])
  
    } else {
    df2 <- data.frame(df[df$State == state, c("Hospital.Name", "Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia")])
    df2$Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia <-      as.numeric(df2$Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia)
    df3 <- order(df2$Hospital.Name)
    df4 <- df2[df3,]
    df5 <- order(df4$Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia)
    df6 <- df4[df5,]
    
    return(df6[1,1])
  }
  
}
  

best("MD", "pneumonia")
  
  
```

```{r}
df <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
df2 <- data.frame(df[df$State == "TX", c("Hospital.Name", "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack")])
df2$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack <-  as.numeric(df2$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack)
df3 <- order(df2$Hospital.Name)
df4 <- df2[df3,]
df5 <- order(df4$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack)
df6 <- df4[df5,]
df6[1,1]

```

```{r}
    df <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
    df2 <- data.frame(df[df$State == "TX", c("Hospital.Name", "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure")])
    df2$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure <-      as.numeric(df2$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure)
    df3 <- order(df2$Hospital.Name)
    df4 <- df2[df3,]
    df5 <- order(df4$Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure)
    df6 <- df4[df5, ]
    df6

```

